# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c809ccc2583dbf56fe93260cc225b3d11fe28e5b58f6cdad05e87da95c779683dc3339397085ec58000c893b848b918b15973405044358ec25427ceafb38cb30

test:
  secret_key_base: 4b1f4b76d361d127fa91815a1a0dd6a42978fcabba2cb00c656e46606190e5b23a31c55f5c4dc668dea8b520e50ad86d8fa0f4ebc691b68e63054b5ad6ff0e9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
